services:
  HalloVerden\Security\Interfaces\AuthenticatorDeciderServiceInterface:
    class: HalloVerden\Security\Services\AuthenticatorDeciderService
    arguments:
      $reader: '@Doctrine\Common\Annotations\Reader'

  HalloVerden\Security\Interfaces\SecurityInterface:
    class: HalloVerden\Security\Security
    arguments:
      $security: '@Symfony\Component\Security\Core\Security'
      $accessDecisionManager: '@Symfony\Component\Security\Core\Authorization\AccessDecisionManagerInterface'

  hv.security_bundle.access_definitions.file_locator:
    class: Metadata\Driver\FileLocator
    arguments:
      $dirs: []

  HalloVerden\Security\AccessDefinitions\Metadata\Drivers\AccessDefinitionYamlDriver:
    arguments:
      $locator: '@hv.security_bundle.access_definitions.file_locator'

  HalloVerden\Security\Interfaces\OauthAuthenticatedAccessTokenProviderServiceInterface:
    class: HalloVerden\Security\Services\OauthAuthenticatedAccessTokenProviderService
    arguments:
      $tokenStorage: '@security.token_storage'

  HalloVerden\Security\Voters\OauthAuthorizationVoter:
    arguments:
      $security: '@HalloVerden\Security\Interfaces\SecurityInterface'
      $accessTokenProvider: '@HalloVerden\Security\Interfaces\OauthAuthenticatedAccessTokenProviderServiceInterface'
    tags:
      - { name: security.voter }

  hv.security.access_definitions.metadata_factory:
    class: Metadata\MetadataFactory
    arguments:
      $driver: '@HalloVerden\Security\AccessDefinitions\Metadata\Drivers\AccessDefinitionYamlDriver'

  HalloVerden\Security\Interfaces\AccessDefinitionServiceInterface:
    class: HalloVerden\Security\Services\AccessDefinitionService
    arguments:
      $metadataFactory: '@hv.security.access_definitions.metadata_factory'
      $security: '@HalloVerden\Security\Interfaces\SecurityInterface'
